spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance_id:${random.value}}
server:
  port: 0

mq:
  queue:
    emissao-cartoes: 'emissao-cartoes'